# Generated by Django 6.0.3 on 2026-03-22 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(default='FPP - Front Patriotique Panafricain', max_length=200)),
                ('slogan', models.CharField(blank=True, default='', max_length=300)),
                ('president_name', models.CharField(blank=True, default='', max_length=200)),
                ('president_message', models.TextField(blank=True, default='')),
                ('president_photo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=20)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.TextField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('twitter_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('hero_title', models.CharField(blank=True, default='', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='')),
                ('about_text', models.TextField(blank=True, default='')),
                ('vision_text', models.TextField(blank=True, default='')),
                ('values_text', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Paramètres du site',
                'verbose_name_plural': 'Paramètres du site',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
