# Generated by Django 6.0.3 on 2026-04-04 03:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BureauMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('title', models.CharField(help_text='Fonction ou titre au sein du parti', max_length=300)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='bureau/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Membre du bureau',
                'verbose_name_plural': 'Membres du bureau',
                'ordering': ['order', 'created_at'],
                'abstract': False,
            },
        ),
    ]
