# Generated by Django 6.0.3 on 2026-04-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpartyrole',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
