# Generated by Django 6.0.3 on 2026-04-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
