# Generated by Django 6.0.3 on 2026-04-02 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_article_is_featured_alter_article_published_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('youtube', 'YouTube')], max_length=20)),
                ('embed_type', models.CharField(choices=[('video', 'Vidéo'), ('post', 'Publication')], default='video', help_text="'video' pour les vidéos/reels, 'post' pour les publications Facebook.", max_length=20)),
                ('source_url', models.URLField(help_text='URL Facebook complète ou ID vidéo YouTube.', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Contenu média',
                'verbose_name_plural': 'Contenus médias',
                'ordering': ['-published_at'],
                'abstract': False,
            },
        ),
    ]
