# Generated by Django 6.0.3 on 2026-04-02 06:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_mediacontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Introduction ou résumé de la section.')),
                ('icon', models.CharField(blank=True, default='', help_text="Nom d'icône Lucide (ex: graduation-cap, heart-pulse, landmark).", max_length=50)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='programme/sections/')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage.")),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'Section du programme',
                'verbose_name_plural': 'Sections du programme',
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=320, unique=True)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, default='', help_text='Résumé court pour les listes.', max_length=500)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/')),
                ('event_type', models.CharField(choices=[('meeting', 'Réunion'), ('rally', 'Rassemblement'), ('conference', 'Conférence'), ('workshop', 'Atelier'), ('ceremony', 'Cérémonie'), ('campaign', 'Campagne'), ('other', 'Autre')], db_index=True, default='other', max_length=20)),
                ('status', models.CharField(choices=[('upcoming', 'À venir'), ('ongoing', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], db_index=True, default='upcoming', max_length=20)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('map_url', models.URLField(blank=True, default='', max_length=500)),
                ('organizer', models.CharField(blank=True, default='', max_length=200)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-start_date'],
                'abstract': False,
                'indexes': [models.Index(fields=['status', '-start_date'], name='idx_event_status_date')],
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Détail de la mesure.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='content.programsection')),
            ],
            options={
                'verbose_name': 'Mesure du programme',
                'verbose_name_plural': 'Mesures du programme',
                'ordering': ['order', 'title'],
                'abstract': False,
            },
        ),
    ]
