# Generated by Django 6.0.3 on 2026-04-05 15:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_programsection_event_programitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('category', models.CharField(choices=[('statuts', 'Statuts & Règlements'), ('rapport', 'Rapports'), ('communique', 'Communiqués'), ('formulaire', 'Formulaires'), ('autre', 'Autre')], db_index=True, default='autre', max_length=30)),
                ('is_public', models.BooleanField(db_index=True, default=False, help_text='Si coché, le document sera visible sur la page publique.')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Taille en octets.')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
                'permissions': [('can_manage_documents', 'Peut gérer les documents')],
                'abstract': False,
            },
        ),
    ]
