# Generated by Django 6.0.3 on 2026-04-04 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_emergency_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cgu_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='CGU acceptées le'),
        ),
        migrations.AddField(
            model_name='user',
            name='cgu_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP lors du consentement'),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy_accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Politique de confidentialité acceptée le'),
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('cgu', "Conditions Générales d'Utilisation"), ('privacy', 'Politique de Confidentialité')], max_length=10)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal de consentement',
                'verbose_name_plural': 'Journaux de consentement',
                'ordering': ['-accepted_at'],
            },
        ),
    ]
