# Generated by Django 6.0.3 on 2026-03-22 22:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matricule', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('sex', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profession', models.CharField(blank=True, default='', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('region', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('commune', models.CharField(db_index=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, default='', max_length=100)),
                ('motivation', models.TextField(blank=True, default='')),
                ('membership_status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('suspended', 'Suspendu'), ('rejected', 'Rejeté')], db_index=True, default='pending', max_length=20)),
                ('membership_date', models.DateTimeField(blank=True, null=True)),
                ('registration_source', models.CharField(choices=[('web', 'Site web'), ('mobile', 'Application mobile'), ('admin', 'Saisie admin')], default='web', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil membre',
                'verbose_name_plural': 'Profils membres',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
