# Generated by Django 6.0.3 on 2026-04-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='sex',
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='id_document_number',
            field=models.CharField(db_index=True, default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='id_document_scan',
            field=models.ImageField(default='', upload_to='members/id_documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='id_document_type',
            field=models.CharField(choices=[('cni', "Carte Nationale d'Identité"), ('passport', 'Passeport'), ('driver_license', 'Permis de conduire')], default='cni', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='matricule',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='photo',
            field=models.ImageField(default='N/A', upload_to='members/photos/'),
            preserve_default=False,
        ),
    ]
